### ISSUE TITLE
Два одинаковых Readme-файла

### ISSUE THREAD

**Issue by Menelion** [BogdanRadionov/nvda-UsefulDictionary#1]
Бодя, привет!  
Во-первых, поздравляю с первым аддоном!  
А во-вторых, хотел сказать, что у тебя есть и `readme.md`, и `readme.txt`. Рекомендую оставить один (например, `readme.md`). Или это требуется правилами NVDA?)

**Comment by BogdanRadionov** [comment]
Привет, Андрюх )
Сенкс за грац с дебютом, два ридми, как это не странно, я держу по 
следующим причинам -- один прикреплен к страничке гитхаба, как общий 
дескрипшн, а второй для тех, кто скачает это дело по прямой ссылке и 
будет энтером туцать на ридми, чтобы он открылся и прочелся. :-)

27.03.2016 2:16, Andre Polykanine A.K.A. Menelion Elensúlë пишет:
